### ISSUE TITLE
Values for metering_point_id and api_key

### ISSUE THREAD

**Issue by GunnarBjoru** [Danielhiversen/home_assistant_glitre#2]
Hi Daniel, regarding home_assistant_glitre.
Should the _metering_point_id_ and the _api_key_ be inside quotation marks (single or double) or not?
I got the api_key from Glitre today, but yet the _sensor.pris_forbruksledd_ is _unknown_

BR Gunnar

**Comment by Danielhiversen** [comment]
Quotations should not be needed.
Any errors in the log?


<img width="204" alt="image" src="https://user-images.githubusercontent.com/650502/199510558-6b63d884-6a90-409f-9d11-a1115cceccfd.png">

**Comment by GunnarBjoru** [comment]
2 errors in the log.

Error 1:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/glitre/sensor.py:42
Integration: Glitre (documentation, issues)
First occurred: 3:22:15 PM (1 occurrences)
Last logged: 3:22:15 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/glitre/sensor.py", line 42, in _handle_coordinator_update
    native_value = self.coordinator.data["forbruksledd"][
KeyError: 'forbruksledd'


Error 2:

This error originated from a custom integration.

Logger: custom_components.glitre.data_coordinator
Source: custom_components/glitre/glitre_api.py:25
Integration: Glitre (documentation, issues)
First occurred: 3:22:15 PM (1 occurrences)
Last logged: 3:22:15 PM

Error fetching Glitre data
Traceback (most recent call last):
  File "/config/custom_components/glitre/data_coordinator.py", line 35, in _async_update_data
    data["forbruksledd"] = await get_glitre_forbruksledd_data(
  File "/config/custom_components/glitre/glitre_api.py", line 25, in get_glitre_forbruksledd_data
    grid_tariff = json_resp["gridTariffCollections"][0]["gridTariff"]
TypeError: 'NoneType' object is not subscriptable

**Comment by Danielhiversen** [comment]
Hmm, I probably need to add some more error handling.


Are you sure the metering_point_id is correct?

You can find it here https://developer.tibber.com/explorer


```
{
  viewer {
    homes {
      meteringPointData {
        consumptionEan
      }
      address {
        address1
      }
    }
  }
}
```

**Comment by GunnarBjoru** [comment]
Ah! I found _MålepunkID_ on my invoice from Glitre and used that as the _metering_point_id_.
When I used your way of finding it the problem was solved.
Thank you Daniel!

**Comment by GunnarBjoru** [comment]
Thak's again!

**Comment by Danielhiversen** [comment]
Understand the confusion.

I will try to improve the error handling here.
