### ISSUE TITLE
Rounding of the price

### ISSUE THREAD

**Issue by grotteru** [Danielhiversen/home_assistant_glitre#3]
First of all, thank you for developing this component @Danielhiversen.

I have a question about rounding. From Glitre Energi Netts [webpages](https://www.glitreenergi-nett.no/kunde/alt-om-nettleiepriser/nettleiepriser/) i can see that the energy component of the tariff is 47,25 øre/kWh. The sensor i get in HA gives me the value 0,47 NOK/kWh. Would it be better to provide the sensor with 4 decimals or give the user the possibility to choose the number of decimals?

BR Magnus

**Comment by Danielhiversen** [comment]
Good point. Will fix

**Comment by GunnarBjoru** [comment]
I cannot see that HACS tell that it has been updated.
Does it need to get a Release Version higher than 0.0.1?

BR Gunnar
