### ISSUE TITLE
Glitre grid price not correct?

### ISSUE THREAD

**Issue by GunnarBjoru** [Danielhiversen/home_assistant_glitre#6]
Glitre Energi Nett has reduced the grid price since January 1st to 0.3865 NOK
But my sensor.pris_forbruksledd shows the value 0.464625
Is it the integration or the data from Glitre which is causing this?
Or maybe it is something on my side?

BR Gunnar

**Comment by hansahell** [comment]
> Glitre Energi Nett has reduced the grid price since January 1st to 0.3865 NOK But my sensor.pris_forbruksledd shows the value 0.464625 Is it the integration or the data from Glitre which is causing this? Or maybe it is something on my side?
> 
> BR Gunnar

The bug was in Glitre's API. After I made them aware of the problem, they found and fixed the bug. The correct prize is now shown in HA.

**Comment by GunnarBjoru** [comment]
> > Glitre Energi Nett has reduced the grid price since January 1st to 0.3865 NOK But my sensor.pris_forbruksledd shows the value 0.464625 Is it the integration or the data from Glitre which is causing this? Or maybe it is something on my side?
> > BR Gunnar
> 
> The bug was in Glitre's API. After I made them aware of the problem, they found and fixed the bug. The correct prize is now shown in HA.

Thank you @hansahell, now it is showing correct for me too.
